/**
 * 资产模板/预设库
 *
 * 三厂（角色 / 场景 / 道具）共用的内置模板数据。
 * 这些模板不依赖 project_id，是全局可用的"快速填表"预设，
 * 前端在新建表单顶部通过下拉/弹窗选择后会自动填充表单。
 *
 * 模板与具体项目/数据库完全解耦：
 * - 写在源代码里硬编码
 * - 通过 GET /api/templates/* 三个接口暴露给前端
 * - 前端只读取不写入（不需要创建/编辑/删除）
 */

import type { Character, Scene, Prop } from "../types/index.js";

/** 角色模板（10 个常用预设，覆盖古风/都市/玄幻/反派/儿童等典型场景）。 */
export const CHARACTER_TEMPLATES: Character[] = [
  {
    id: "tpl-char-01",
    project_id: "",
    name: "林逸",
    role: "protagonist",
    gender: "male",
    age: 20,
    traits: ["勇敢", "机智", "重情义"],
    description: "古风少年剑客，黑发高马尾，身披白袍，眉目清冷，手持三尺青锋剑。自幼被师门收养，怀揣着寻找身世秘密的执念闯荡江湖。",
    tags: ["古风", "主角", "剑客"],
    created_at: "",
    updated_at: "",
  },
  {
    id: "tpl-char-02",
    project_id: "",
    name: "萧晓",
    role: "protagonist",
    gender: "female",
    age: 28,
    traits: ["干练", "独立", "聪慧"],
    description: "都市白领女主，知名广告公司创意总监，短发干练、衣着精致，做事雷厉风行却也有柔软的一面。",
    tags: ["都市", "主角", "白领"],
    created_at: "",
    updated_at: "",
  },
  {
    id: "tpl-char-03",
    project_id: "",
    name: "X 先生",
    role: "antagonist",
    gender: "male",
    age: 40,
    traits: ["阴鸷", "高智商", "偏执"],
    description: "反派大佬，常年一身黑色风衣，出场总是伴随着雨夜与古典乐。掌控着庞大的地下商业帝国，与主角有不可调和的恩怨。",
    tags: ["反派", "高智商", "都市"],
    created_at: "",
    updated_at: "",
  },
  {
    id: "tpl-char-04",
    project_id: "",
    name: "云崖老人",
    role: "supporting",
    gender: "male",
    age: 70,
    traits: ["睿智", "慈祥", "神秘"],
    description: "老年智者，白发长髯，常年隐居山林古刹之中，知晓江湖上几乎所有不传之秘，是主角的指路明灯。",
    tags: ["配角", "智者", "古风"],
    created_at: "",
    updated_at: "",
  },
  {
    id: "tpl-char-05",
    project_id: "",
    name: "小七",
    role: "minor",
    gender: "male",
    age: 12,
    traits: ["活泼", "天真", "机灵"],
    description: "童趣少年，机灵古怪的小跟班，擅长观察和偷听，总是在关键时刻带来意外惊喜。",
    tags: ["次要", "少年", "喜剧"],
    created_at: "",
    updated_at: "",
  },
  {
    id: "tpl-char-06",
    project_id: "",
    name: "???",
    role: "supporting",
    gender: "female",
    age: 0,
    traits: ["神秘", "高冷", "身世成谜"],
    description: "神秘女子，登场时总是笼罩在薄雾中，声音空灵，仅以一句诗作为代号，从不透露真实身份。",
    tags: ["配角", "神秘", "玄幻"],
    created_at: "",
    updated_at: "",
  },
  {
    id: "tpl-char-07",
    project_id: "",
    name: "剑灵",
    role: "supporting",
    gender: "other",
    age: 0,
    traits: ["傲娇", "强大", "忠诚"],
    description: "玄幻剑灵，寄宿于主角佩剑之中，平时以少年虚影出现，危急时会化作巨剑显形。",
    tags: ["配角", "剑灵", "玄幻"],
    created_at: "",
    updated_at: "",
  },
  {
    id: "tpl-char-08",
    project_id: "",
    name: "狐妖阿九",
    role: "minor",
    gender: "female",
    age: 18,
    traits: ["狡黠", "妩媚", "脆弱"],
    description: "妖族少年少女相，九尾狐族末裔，外表是 18 岁少女模样，常化作人形在凡间游历。",
    tags: ["次要", "妖族", "玄幻"],
    created_at: "",
    updated_at: "",
  },
  {
    id: "tpl-char-09",
    project_id: "",
    name: "江医生",
    role: "supporting",
    gender: "male",
    age: 35,
    traits: ["温柔", "专业", "宅心仁厚"],
    description: "现代医生角色，三甲医院心外科主治，平日戴着金丝边眼镜，对病人温和有耐心，与女主是青梅竹马。",
    tags: ["配角", "现代", "医生"],
    created_at: "",
    updated_at: "",
  },
  {
    id: "tpl-char-10",
    project_id: "",
    name: "龙渊",
    role: "antagonist",
    gender: "male",
    age: 30,
    traits: ["霸气", "狂傲", "重诺"],
    description: "玄幻反派，魔尊转世，一身玄黑战甲，眉心有红色魔纹，谈笑间可移山填海，与主角宿命对决。",
    tags: ["反派", "玄幻", "魔尊"],
    created_at: "",
    updated_at: "",
  },
];

/** 场景模板（8 个常用预设，覆盖古风/现代/玄幻/室内/室外等典型场景）。 */
export const SCENE_TEMPLATES: Scene[] = [
  {
    id: "tpl-scene-01",
    project_id: "",
    name: "古风街道",
    type: "outdoor",
    description: "青石板路两侧是鳞次栉比的古风木楼，屋檐挂着红灯笼，远处是朦胧的远山与城墙。",
    tags: ["古风", "室外"],
    lighting: "自然光",
    time_of_day: "黄昏",
    weather: "晴",
    created_at: "",
    updated_at: "",
  },
  {
    id: "tpl-scene-02",
    project_id: "",
    name: "现代咖啡馆",
    type: "indoor",
    description: "落地玻璃窗、实木吧台、绿植点缀，下午的暖阳斜照在浅木桌椅上，背景是轻柔的爵士乐。",
    tags: ["现代", "室内"],
    lighting: "暖光",
    time_of_day: "白天",
    weather: "晴",
    created_at: "",
    updated_at: "",
  },
  {
    id: "tpl-scene-03",
    project_id: "",
    name: "夜晚小巷",
    type: "outdoor",
    description: "潮湿的青砖小巷，路灯在头顶发出昏黄的光晕，墙角的积水映着霓虹，远处偶尔有猫叫。",
    tags: ["现代", "室外", "夜景"],
    lighting: "月光",
    time_of_day: "夜晚",
    weather: "阴",
    created_at: "",
    updated_at: "",
  },
  {
    id: "tpl-scene-04",
    project_id: "",
    name: "山林秘境",
    type: "outdoor",
    description: "参天古木与云雾缭绕的幽谷，溪水从苔藓石上滑落，林间透出斑驳日光，偶有仙鹤掠过。",
    tags: ["玄幻", "室外", "秘境"],
    lighting: "自然光",
    time_of_day: "白天",
    weather: "雾",
    created_at: "",
    updated_at: "",
  },
  {
    id: "tpl-scene-05",
    project_id: "",
    name: "室内书房",
    type: "indoor",
    description: "古色古香的书房，红木书案、卷轴、砚台、笔架，墙上挂着山水画，窗外透出竹影。",
    tags: ["古风", "室内", "书房"],
    lighting: "暖光",
    time_of_day: "白天",
    weather: "晴",
    created_at: "",
    updated_at: "",
  },
  {
    id: "tpl-scene-06",
    project_id: "",
    name: "玄幻宫殿",
    type: "virtual",
    description: "悬浮在云端的巍峨宫殿，琉璃金瓦、九龙石柱、银河般的天河从殿前流过，散发七彩霞光。",
    tags: ["玄幻", "虚拟", "宫殿"],
    lighting: "特殊光",
    time_of_day: "夜晚",
    weather: "晴",
    created_at: "",
    updated_at: "",
  },
  {
    id: "tpl-scene-07",
    project_id: "",
    name: "现代教室",
    type: "indoor",
    description: "标准中学教室，排列整齐的课桌椅、投影白板、绿色窗帘、午后斜阳照在木地板上。",
    tags: ["现代", "室内", "校园"],
    lighting: "自然光",
    time_of_day: "白天",
    weather: "晴",
    created_at: "",
    updated_at: "",
  },
  {
    id: "tpl-scene-08",
    project_id: "",
    name: "战场废墟",
    type: "outdoor",
    description: "残垣断壁、燃尽的战旗、插在泥土中的残剑，远处是燃烧的城池与滚滚浓烟。",
    tags: ["玄幻", "室外", "战场"],
    lighting: "特殊光",
    time_of_day: "黄昏",
    weather: "阴",
    created_at: "",
    updated_at: "",
  },
];

/** 道具模板（10 个常用预设，覆盖武器/工具/服饰/神器/食物/家具/载具）。 */
export const PROP_TEMPLATES: Prop[] = [
  {
    id: "tpl-prop-01",
    project_id: "",
    name: "长剑",
    category: "weapon",
    description: "古风长剑，剑身修长、剑柄缠青色丝绦，铸造精良，是剑客的标志性随身兵器。",
    appearance: "三尺青锋，剑鞘上刻有云纹，剑格处镶一颗蓝色宝石。",
    material: "金属",
    size: "长约 1.1m",
    color: "银色",
    tags: ["古风", "武器"],
    created_at: "",
    updated_at: "",
  },
  {
    id: "tpl-prop-02",
    project_id: "",
    name: "古书",
    category: "tool",
    description: "线装古书，记载着上古秘辛与失传的武功心法，封面已略显破旧。",
    appearance: "线装、卷边、封皮以隶书题写书名，偶有虫蛀痕迹。",
    material: "纸质",
    size: "16 开",
    color: "泛黄",
    tags: ["古风", "工具", "书"],
    created_at: "",
    updated_at: "",
  },
  {
    id: "tpl-prop-03",
    project_id: "",
    name: "现代手机",
    category: "tool",
    description: "现代智能手机，全面屏、后置三摄，是当代人日常生活的标志。",
    appearance: "超薄全面屏、玻璃背板、极简设计。",
    material: "金属/玻璃",
    size: "6.7 英寸",
    color: "黑色",
    tags: ["现代", "工具", "数码"],
    created_at: "",
    updated_at: "",
  },
  {
    id: "tpl-prop-04",
    project_id: "",
    name: "玉佩",
    category: "artifact",
    description: "通灵古玉，佩于腰间有安神护体之效，玉中隐约可见流光，常作为信物出现。",
    appearance: "圆形双鱼镂雕，玉质温润、边缘包金。",
    material: "玉石",
    size: "直径 5cm",
    color: "青色",
    tags: ["古风", "神器", "玉"],
    created_at: "",
    updated_at: "",
  },
  {
    id: "tpl-prop-05",
    project_id: "",
    name: "战甲",
    category: "clothing",
    description: "玄幻战甲，由玄铁打造，外覆赤铜鳞片，穿戴后可大幅提升战力。",
    appearance: "覆盆式头盔、肩甲、护臂、护胸、战靴一体，胸前刻有家徽。",
    material: "金属",
    size: "均码可调",
    color: "暗红色",
    tags: ["玄幻", "服饰", "战甲"],
    created_at: "",
    updated_at: "",
  },
  {
    id: "tpl-prop-06",
    project_id: "",
    name: "马车",
    category: "vehicle",
    description: "古风两匹马拉动厢式马车，车厢雕花描金，是古代出行与剧情转换的常用载具。",
    appearance: "乌木车厢、雕花窗格、顶盖镶流苏，车前立两匹枣红马。",
    material: "木质",
    size: "长 3.5m",
    color: "乌木色",
    tags: ["古风", "载具", "马车"],
    created_at: "",
    updated_at: "",
  },
  {
    id: "tpl-prop-07",
    project_id: "",
    name: "灵丹",
    category: "food",
    description: "玄幻灵丹，服用后可短暂提升灵力或恢复伤势，瓶中仅有三颗。",
    appearance: "圆润光洁，表面有流光纹路，置于小瓷瓶中。",
    material: "草药凝练",
    size: "每颗约拇指大小",
    color: "金黄色",
    tags: ["玄幻", "食物", "丹药"],
    created_at: "",
    updated_at: "",
  },
  {
    id: "tpl-prop-08",
    project_id: "",
    name: "丹药炉",
    category: "furniture",
    description: "古风炼丹炉，三足两耳、炉身铸饕餮纹，用于炼制各类丹药。",
    appearance: "三足圆腹两耳炉，炉身铸饕餮与云纹，炉盖镂空以散烟。",
    material: "青铜",
    size: "高 1.2m",
    color: "青铜色",
    tags: ["古风", "家具", "炼丹"],
    created_at: "",
    updated_at: "",
  },
  {
    id: "tpl-prop-09",
    project_id: "",
    name: "古琴",
    category: "tool",
    description: "七弦古琴，琴身断纹清晰，音色空灵，是文人雅士修身之器。",
    appearance: "仲尼式、髹黑漆、断纹如蛇腹，琴徽以螺钿镶嵌。",
    material: "木质",
    size: "长 1.2m",
    color: "黑色",
    tags: ["古风", "工具", "乐器"],
    created_at: "",
    updated_at: "",
  },
  {
    id: "tpl-prop-10",
    project_id: "",
    name: "飞剑",
    category: "artifact",
    description: "玄幻飞剑，可御剑飞行，千里之外取人首级，是剑修梦寐以求的宝物。",
    appearance: "短剑形态，剑身有云纹流转，注入灵力后可化作流光放大数倍。",
    material: "玄铁/灵玉",
    size: "长 0.5m，可变化",
    color: "银白色",
    tags: ["玄幻", "神器", "飞剑"],
    created_at: "",
    updated_at: "",
  },
];

/** 返回全部角色模板（直接返回常量引用，避免深拷贝）。 */
export function listCharacterTemplates(): Character[] {
  return CHARACTER_TEMPLATES;
}

/** 返回全部场景模板。 */
export function listSceneTemplates(): Scene[] {
  return SCENE_TEMPLATES;
}

/** 返回全部道具模板。 */
export function listPropTemplates(): Prop[] {
  return PROP_TEMPLATES;
}
