export interface Timebase { fpsNumerator: number; fpsDenominator: number; dropFrame: boolean }
export interface EffectInstance { id: string; effectType: string; implementationId: string; implementationVersion: string; enabled: boolean; parameters: Record<string, unknown>; parameterSchemaVersion: number }
export interface VideoClip { id: string; trackId: string; sourceType: "shot_video" | "uploaded_video" | "rendered_video"; sourceId: string; sourceVersion: number; sourceContentHash: string; presentationSnapshotId: string | null; sourceInMs: number; sourceOutMs: number; timelineStartMs: number; playbackRate: number; opacity: number; effects: EffectInstance[]; sortKey: string }
export interface AudioClip { id: string; trackId: string; audioAssetId: string; sourceVersion: number; sourceContentHash: string; sourceInMs: number; sourceOutMs: number; timelineStartMs: number; playbackRate: number; gainDb: number; pan: number; fadeInMs: number; fadeOutMs: number; effects: EffectInstance[] }
export interface TimelineSubtitleCue { id: string; trackId: string; subtitleDocumentId: string | null; subtitleDocumentVersion: number | null; sourceCueId: string | null; textSnapshot: string; startMs: number; endMs: number }
export interface Transition { id: string; trackId: string; fromClipId: string; toClipId: string; type: "cut" | "dissolve" | "fade" | "wipe" | "custom"; durationMs: number; implementationId: string; implementationVersion: string; parameters: Record<string, unknown> }
export interface Timeline { timebase: Timebase; durationMs: number; videoTracks: Array<{ id: string; name: string; order: number; locked: boolean; muted: boolean; hidden: boolean; compositingMode: string; clips: VideoClip[] }>; audioTracks: Array<{ id: string; name: string; order: number; role: string; locked: boolean; muted: boolean; solo: boolean; gainDb: number; clips: AudioClip[] }>; subtitleTracks: Array<{ id: string; name: string; order: number; language: string; locked: boolean; hidden: boolean; cues: TimelineSubtitleCue[] }>; transitions: Transition[] }
export interface EditProjectSummary { id: string; name?: string; status: "draft" | "rendering" | "ready" | "archived"; currentRevision: number; version: number; timeline: Timeline }

